=== RaulRedondo1969/MEDAC2/MEDAC2/lasventas.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ventas (venta*)>
<!ELEMENT venta (fecha,coche,nombre_vendedor?,nombre_comprador?)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT coche (marca,modelo,potencia)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT nombre_vendedor (#PCDATA)>
<!ELEMENT nombre_comprador (#PCDATA)>

=== RaulRedondo1969/MEDAC2/MEDAC2/ejemplo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ventas SYSTEM "lasventas.dtd">
<ventas>
	<venta>
	
	<fecha>22-09-200</fecha>
	<coche>
		<marca>Audi</marca>
		<modelo>A3</modelo>
		<potencia>1200</potencia>
	</coche>
	<nombre_vendedor>Raul</nombre_vendedor>
	<nombre_comprador>Alberto</nombre_comprador>
	</venta>
	


</ventas>
